plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
relative_links:
  enabled: true
  collections: true
header_pages:
  - index.html
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-tactile
