remote_theme: sujoy-saha/Jekyll-Theme
exclude:
  - readme.md  
header_pages:
  - index.html
author: Sujoy Kumar Saha
github_username:  sujoy-saha
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
